const texts = [
  {
    title: "A Journey to Peru",
    text: "Sarah, a young English student at B1 level, had always dreamed of traveling to far-off places. One day, her dream came true when she embarked on a journey to Peru. Excited but a bit nervous, she boarded the plane, ready for the adventure ahead. Upon landing in Lima, the capital city of Peru, Sarah was greeted by the bustling streets filled with colorful markets and friendly faces. Despite the language barrier, she managed to communicate with locals using simple phrases she had learned in her English class. Her first stop was Cusco, the gateway to the ancient Inca city of Machu Picchu. Sarah marveled at the breathtaking views of the Andes Mountains as she hiked along the Inca Trail. Along the way, she encountered llamas grazing in the meadows and learned about the rich history of the Incas from her tour guide. After a few days in Cusco, Sarah traveled to the Sacred Valley, where she explored the ruins of Ollantaytambo and visited indigenous communities. She tried traditional Peruvian dishes like ceviche and lomo saltado, delighting in the unique flavors of the local cuisine. The highlight of Sarah's trip was finally reaching Machu Picchu. As she stood atop the ancient citadel, surrounded by mist-covered mountains, she felt a sense of awe and wonder. It was a moment she would never forget. As her journey came to an end, Sarah realized how much she had learned and grown from her experiences in Peru. With memories to last a lifetime, she returned home with a newfound appreciation for the beauty and diversity of the world.",
  },
  {
    title: "Exploring Thailand's Wonders",
    text: "As a B1 level English student, embarking on a journey to Thailand was an exciting adventure for Lily. With her backpack filled with essentials, she set off to explore the vibrant and enchanting land of smiles. Her first stop was Bangkok, the bustling capital city. The streets were alive with the hustle and bustle of tuk-tuks and street vendors. Lily marveled at the ornate temples, such as Wat Pho and the Grand Palace, adorned with intricate designs and shimmering golden spires. Venturing further, Lily traveled north to Chiang Mai, a city nestled amidst lush green mountains. Here, she immersed herself in Thai culture by taking a cooking class, learning to whip up delicious dishes like pad Thai and green curry. Next, Lily journeyed to the serene beaches of southern Thailand. With its turquoise waters and powdery white sands, Phuket was a paradise unlike any other. She spent her days snorkeling in crystal-clear waters, admiring the colorful marine life, and basking in the warm tropical sun. One of the highlights of Lily's trip was exploring the ancient ruins of Ayutthaya, a UNESCO World Heritage Site. As she wandered among the crumbling temples and towering pagodas, she felt a sense of wonder and awe at Thailand's rich history and heritage. As her journey came to an end, Lily reflected on her time in Thailand with fond memories. She had learned new words and phrases, experienced the warmth and hospitality of the Thai people, and gained a deeper appreciation for the beauty and diversity of the world. Thailand had truly captured her heart, and she knew she would cherish the memories of her travels for years to come.",
    qestions: [
      "Bangkok is described as a quiet and serene capital city.",
      "Phuket is depicted as a bustling city with towering skyscrapers",
      "Ayutthaya is mentioned as a UNESCO World Heritage Site known for its ancient ruins.",
    ],
  },
  {
    title: "The Political Landscape of the USA",
    text: "For English learners at the B1 level, understanding the political dynamics of the United States is essential. The USA operates under a democratic system, where citizens elect representatives to govern at the local, state, and federal levels. At the heart of American politics are the two major political parties: the Democratic Party and the Republican Party. These parties often hold differing views on key issues such as healthcare, immigration, and the economy. Every four years, the nation comes together for a presidential election. Candidates from each party compete in a series of primaries and caucuses to win their party's nomination. The presidential election culminates in a nationwide vote known as the general election, where citizens cast their ballots to determine the next president of the United States. In addition to the president, other important political positions include members of Congress and state governors. Congress is divided into two chambers: the House of Representatives and the Senate. Representatives are elected from congressional districts, while senators represent entire states. Together, they form the legislative branch of government and are responsible for making and passing laws. The political landscape in the USA is often characterized by lively debate and passionate discourse. Citizens engage in political activism through various means, including voting, advocacy, and community organizing. While differences of opinion may arise, the democratic process serves as a foundation for the nation's governance, ensuring that diverse voices are heard and represented.",
  },
  {
    title: "Thanksgiving Tradition in the USA",
    text: "For English learners at the B1 level, understanding cultural traditions like Thanksgiving in the United States is a valuable part of language learning. Thanksgiving is a national holiday celebrated on the fourth Thursday of November each year. The origins of Thanksgiving trace back to a harvest feast shared between the Pilgrims and Native Americans in 1621. Today, it is a time for families and friends to come together, express gratitude, and enjoy a hearty meal. The centerpiece of the Thanksgiving feast is often a roasted turkey, accompanied by an array of side dishes such as mashed potatoes, stuffing, cranberry sauce, and pumpkin pie. Families gather around the table, sharing stories and memories while indulging in the delicious spread. In addition to food, Thanksgiving is also associated with other traditions. Many communities hold parades featuring elaborate floats, marching bands, and giant balloons. The most famous of these is the Macy's Thanksgiving Day Parade in New York City, which attracts millions of spectators each year. Another popular tradition is watching American football games on television. The National Football League (NFL) hosts several games on Thanksgiving Day, drawing sports fans of all ages. Beyond the feasting and festivities, Thanksgiving is a time for reflection and gratitude. It offers an opportunity for individuals to pause and appreciate the blessings in their lives, whether it be family, friends, health, or happiness. Overall, Thanksgiving is a cherished holiday in the United States, symbolizing unity, gratitude, and the spirit of togetherness. It serves as a reminder to pause and give thanks for the abundance in our lives, fostering a sense of appreciation and community.",
  },
  {
    title: "Understanding the School System in the USA",
    text: "For English learners at the B1 level, gaining insight into the school system in the United States is crucial. The education system in the USA is diverse and multifaceted, encompassing various levels of schooling, from early childhood education to higher education. Elementary school, also known as primary school, typically spans from kindergarten to fifth or sixth grade, depending on the state. Here, children learn fundamental subjects such as math, English language arts, science, and social studies. They also participate in extracurricular activities like art, music, and physical education. Following elementary school, students move on to middle school or junior high school, which typically covers grades six through eight. Here, students continue to build upon their foundational knowledge while also exploring more specialized subjects. High school is the final stage of compulsory education in the USA and typically consists of grades nine through twelve. During these years, students have the opportunity to take a wide range of courses, including advanced placement (AP) classes and elective subjects. Additionally, students may participate in extracurricular activities such as sports teams, clubs, and student government. Upon completing high school, students have the option to pursue higher education at colleges, universities, or vocational schools. Higher education institutions in the USA offer a wide array of academic programs and degrees, ranging from associate's degrees to bachelor's, master's, and doctoral degrees. Overall, the school system in the USA emphasizes the importance of academic achievement, personal development, and lifelong learning. It provides students with opportunities to explore their interests, cultivate their talents, and prepare for success in an ever-changing world.",
  },
];

export default texts;
